# Site settings
title: Antonio Franca | ML Researcher
email: your-email@example.com
description: >-
  Personal website of Antonio Franca, Machine Learning researcher 
  focusing on computational neuroscience and AI.
baseurl: "" # For user or organization sites, leave this empty
url: "https://antoniofranca.github.io" # Replace with your GitHub Pages URL
author: Antonio Franca

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:title/

# Defaults for various content
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      blog_active: true

# Build settings
permalink: pretty
markdown: kramdown
sass:
  style: compressed

# Jekyll 3 settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Jekyll 4 settings
include:
  - _pages

exclude:
  - README.md
  - templates/
  - config.json
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git

# Social links
social:
  twitter: https://twitter.com/antoniofranca
  github: https://github.com/antoniofranca
  google_scholar: https://scholar.google.com/citations?user=antonio-franca

# Navigation
navigation:
  - name: home
    url: /
  - name: blog
    url: /blog/
  - name: cv
    url: /cv/
  - name: research
    url: /research/ 