[build]
  functions = "netlify/functions"
  publish = "."

[functions]
  node_bundler = "nft"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Environment variables (you'll set these in Netlify dashboard)
# NOTION_API_KEY = "your_notion_integration_token"
# NOTION_DATABASE_ID = "your_notion_database_id"
